services:
  db:
    image: postgres:16-alpine
    container_name: eventmaster_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventmaster
      POSTGRES_PASSWORD: eventmaster123
      POSTGRES_DB: eventmaster_pro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
