// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migraciones: usar conexión directa (no pooler) para evitar timeouts en Neon free tier
    // DATABASE_URL_UNPOOLED = direct connection | POSTGRES_URL = pooler (runtime)
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["POSTGRES_URL_NON_POOLING"] ?? process.env["POSTGRES_URL"] ?? process.env["DATABASE_URL"],
  },
});
